#!/usr/bin/env sh

if [ "$(whoami)" != "root" ]; then
    SUDO=sudo
fi

curl -sL https://artifacts.elastic.co/GPG-KEY-elasticsearch | ${SUDO} apt-key add -
${SUDO} sh -c 'echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list'
${SUDO} apt-get update
${SUDO} apt-get -y install elasticsearch
