#!/usr/bin/env sh

curl -sL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
sudo sh -c 'echo "deb http://nginx.org/packages/mainline/debian `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list'
sudo apt-get update
sudo apt-get -y install nginx
