#!/usr/bin/env sh

if [ "$(whoami)" != "root" ]; then
    SUDO=sudo
fi

curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | ${SUDO} apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | ${SUDO} tee /etc/apt/sources.list.d/yarn.list
${SUDO} apt-get update && ${SUDO} apt-get -y install yarn
